[package]
name = "cases"
version = "0.0.0"
edition = "2021"
publish = false
include = ["/src/**/*", "/*.py", "/*.pyi", "/LICENSE", "/README.md"]

[lib]
name = "cases"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.19.0"
